// Build a single self-contained HTML report for a theme run.
// Reads runs/<THEME_ID>/results.json (Playwright JSON) + runs/<THEME_ID>/validate.json
// and writes runs/<THEME_ID>/report.html — one file, screenshots inlined, opens anywhere.
//
// Usage:  THEME_ID=<id> node scripts/build_report.js   (or: node scripts/build_report.js <themeId>)
import fs from 'fs';
import path from 'path';

const themeId = process.env.THEME_ID || process.argv[2] || 'default';
const base = `runs/${themeId}`;
const read = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { return null; } };

const validate = read(`${base}/validate.json`);
const pw = read(`${base}/results.json`);

const tests = [];
if (pw?.suites) {
  const walk = (s, file) => {
    const f = s.file || file;
    (s.specs || []).forEach((spec) => spec.tests.forEach((t) => {
      const r = t.results?.[t.results.length - 1] || {};
      const shots = (r.attachments || []).filter((a) => a.contentType === 'image/png' && a.path && fs.existsSync(a.path));
      tests.push({
        title: spec.title, file: f, project: t.projectName || '',
        status: r.status || 'unknown',
        error: (r.error && (r.error.message || '')) || '',
        annotations: (t.annotations || []).map((a) => a.description).filter(Boolean),
        shots,
      });
    }));
    (s.suites || []).forEach((x) => walk(x, f));
  };
  pw.suites.forEach((s) => walk(s));
}

const counts = tests.reduce((a, t) => (a[t.status] = (a[t.status] || 0) + 1, a), {});
const passed = (counts.passed || 0) + (counts.expected || 0);
const failed = tests.filter((t) => !['passed','expected','skipped'].includes(t.status)).length;
const skipped = counts.skipped || 0;
const structuralPass = validate ? validate.passed_gate !== false : null;
const overall = failed === 0 && structuralPass !== false;

const esc = (s) => String(s || '').replace(/[&<>]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const b64 = (p) => { try { return 'data:image/png;base64,' + fs.readFileSync(p).toString('base64'); } catch { return ''; } };

const badge = (st) => {
  const map = { passed:'#2f855a', expected:'#2f855a', failed:'#c53030', 'timedOut':'#c53030', skipped:'#a0aec0', unknown:'#a0aec0' };
  return `<span style="background:${map[st]||'#a0aec0'};color:#fff;padding:2px 8px;border-radius:10px;font-size:11px">${st}</span>`;
};

const rows = tests.map((t) => `
  <tr>
    <td style="white-space:nowrap">${badge(t.status)}</td>
    <td><b>${esc(t.title)}</b> <span style="color:#888">${esc(t.project)}</span>
      ${t.error ? `<div style="color:#c53030;font-size:12px;margin-top:4px;white-space:pre-wrap">${esc(t.error).slice(0,600)}</div>` : ''}
      ${t.annotations.length ? `<div style="color:#b7791f;font-size:12px;margin-top:4px">⚠ ${esc(t.annotations.join(' | ')).slice(0,400)}</div>` : ''}
      ${t.shots.map((s) => `<div><img src="${b64(s.path)}" style="max-width:520px;border:1px solid #ddd;border-radius:6px;margin-top:6px"></div>`).join('')}
    </td>
  </tr>`).join('');

const html = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8">
<title>Theme QA Report — ${esc(themeId)}</title>
<style>body{font-family:system-ui,Segoe UI,Tahoma,sans-serif;margin:24px;color:#1a1a1a}
h1{font-size:20px} table{border-collapse:collapse;width:100%} td{border-bottom:1px solid #eee;padding:8px;vertical-align:top}
.sum{display:flex;gap:16px;flex-wrap:wrap;margin:12px 0}
.card{border:1px solid #e2e8f0;border-radius:8px;padding:12px 16px;min-width:120px}
.big{font-size:22px;font-weight:700}</style></head><body>
<h1>تقرير اختبار الثيم — ${esc(themeId)}</h1>
<div style="font-size:20px;font-weight:700;color:${overall?'#2f855a':'#c53030'}">${overall?'✅ PASS':'❌ FAIL'}</div>
<div class="sum">
  <div class="card"><div class="big">${validate ? `${validate.passed}/${validate.total}` : '—'}</div>Structural templates</div>
  <div class="card"><div class="big" style="color:#2f855a">${passed}</div>E2E passed</div>
  <div class="card"><div class="big" style="color:#c53030">${failed}</div>E2E failed</div>
  <div class="card"><div class="big" style="color:#a0aec0">${skipped}</div>skipped</div>
</div>
<p style="color:#666">Structural gate (/validate): <b>${structuralPass===null?'not run':structuralPass?'PASS':'FAIL'}</b>
${validate?.failing_templates?.length ? ' · failing: ' + esc(validate.failing_templates.join(', ')) : ''}</p>
<table>${rows || '<tr><td>No E2E results found. Run: npx playwright test</td></tr>'}</table>
<p style="color:#aaa;font-size:12px;margin-top:20px">Generated by zid-theme-qa</p>
</body></html>`;

fs.mkdirSync(base, { recursive: true });
const outPath = path.join(base, 'report.html');
fs.writeFileSync(outPath, html);
console.log(`Report written: ${outPath}  (${passed} passed, ${failed} failed, ${skipped} skipped)`);
